// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TS.Migrations
{
    [DbContext(typeof(Demo3Context))]
    partial class Demo3ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TS.GiaTien", b =>
                {
                    b.Property<string>("GiaTienId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("GiaTiens")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("GiaTienId");

                    b.ToTable("GiaTien");
                });

            modelBuilder.Entity("TS.HSX", b =>
                {
                    b.Property<string>("HSXId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HSXs")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("HSXId");

                    b.ToTable("HSX");
                });

            modelBuilder.Entity("TS.KieuKhachHang", b =>
                {
                    b.Property<string>("KKHId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("KKH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("KKHId");

                    b.ToTable("KieuKhachHang");
                });

            modelBuilder.Entity("TS.LKPC", b =>
                {
                    b.Property<string>("LKPCId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LKPCName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LKPCId");

                    b.ToTable("LKPC");
                });

            modelBuilder.Entity("TS.LinhKienPC", b =>
                {
                    b.Property<string>("LinhKienPCId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HSXs")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LinhKienPCName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LinhKienPCId");

                    b.ToTable("LinhKienPC");
                });

            modelBuilder.Entity("TS.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentName")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("TS.TinhNang", b =>
                {
                    b.Property<string>("TNId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TNId");

                    b.ToTable("TinhNang");
                });
#pragma warning restore 612, 618
        }
    }
}
